


name: Release Drafter

on:
  push:
    branches:
      - master


jobs:
  make-draft:
    runs-on: ubuntu-latest

    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

